/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './message.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/common';
import * as i3 from './message.component';
import * as i4 from '../../messages.service';
const styles_MessageComponent:any[] = [i0.styles];
export const RenderType_MessageComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MessageComponent,data:{}});
function View_MessageComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'config panel-default']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n            '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'a',[['class','btn btn-primary']],(null as any),
      [[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onEdit()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['Edit'])),(_l()(),
      i1.ɵted((null as any),['\n            '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      1,'a',[['class','btn btn-danger']],(null as any),[[(null as any),'click']],(_v,
          en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onDelete()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['Delete'])),(_l()(),
      i1.ɵted((null as any),['\n        ']))],(null as any),(null as any));
}
export function View_MessageComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),13,'article',[['class',
      'panel panel-default']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'div',[['class','panel panel-body']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n        ','\n    '])),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),7,'footer',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
      ['\n        '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'author']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n            ','\n        '])),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),1,
          (null as any),View_MessageComponent_1)),i1.ɵdid(16384,(null as any),0,i2.NgIf,
          [i1.ViewContainerRef,i1.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),(_l()(),
          i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        var _co:i3.MessageComponent = _v.component;
        const currVal_2:any = _co.belongsToUser();
        _ck(_v,11,0,currVal_2);
      },(_ck,_v) => {
        var _co:i3.MessageComponent = _v.component;
        const currVal_0:any = _co.message.content;
        _ck(_v,3,0,currVal_0);
        const currVal_1:any = _co.message.username;
        _ck(_v,8,0,currVal_1);
      });
}
export function View_MessageComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-message',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessageComponent_0,
      RenderType_MessageComponent)),i1.ɵdid(114688,(null as any),0,i3.MessageComponent,
      [i4.MessagesService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessageComponentNgFactory:i1.ComponentFactory<i3.MessageComponent> = i1.ɵccf('app-message',
    i3.MessageComponent,View_MessageComponent_Host_0,{message:'inputMessage'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy1saXN0L21lc3NhZ2UvbWVzc2FnZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy1saXN0L21lc3NhZ2UvbWVzc2FnZS5jb21wb25lbnQudHMiLCJuZzovLy9DOi9NRUFOL21haW4tcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLWxpc3QvbWVzc2FnZS9tZXNzYWdlLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy1saXN0L21lc3NhZ2UvbWVzc2FnZS5jb21wb25lbnQudHMuTWVzc2FnZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxhcnRpY2xlIGNsYXNzPVwicGFuZWwgcGFuZWwtZGVmYXVsdFwiPlxuICAgIDxkaXYgY2xhc3M9XCJwYW5lbCBwYW5lbC1ib2R5XCI+XG4gICAgICAgIHt7IG1lc3NhZ2UuY29udGVudCB9fVxuICAgIDwvZGl2PlxuICAgIDxmb290ZXI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJhdXRob3JcIj5cbiAgICAgICAgICAgIHt7IG1lc3NhZ2UudXNlcm5hbWUgfX1cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb25maWcgcGFuZWwtZGVmYXVsdFwiICpuZ0lmPVwiYmVsb25nc1RvVXNlcigpXCI+XG4gICAgICAgICAgICA8YSBjbGFzcz1cImJ0biBidG4tcHJpbWFyeVwiIChjbGljayk9XCJvbkVkaXQoKVwiPkVkaXQ8L2E+XG4gICAgICAgICAgICA8YSBjbGFzcz1cImJ0biBidG4tZGFuZ2VyXCIgKGNsaWNrKT1cIm9uRGVsZXRlKClcIj5EZWxldGU8L2E+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZm9vdGVyPlxuPC9hcnRpY2xlPiIsIjxhcHAtbWVzc2FnZT48L2FwcC1tZXNzYWdlPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ1FRO01BQUE7TUFBQSxnQkFBMEQsbURBQ3REO01BQUE7TUFBQTtRQUFBO1FBQUE7UUFBMkI7VUFBQTtVQUFBO1FBQUE7UUFBM0I7TUFBQSxnQ0FBOEMseUNBQVE7YUFBQSxvQ0FDdEQ7TUFBQTttQkFBQTtRQUFBO1FBQUE7UUFBMEI7VUFBQTtVQUFBO1FBQUE7UUFBMUI7TUFBQSxnQ0FBK0MsMkNBQVU7YUFBQTs7O29CQVZyRTtNQUFBO01BQUEsZ0JBQXFDLDJDQUNqQztNQUFBO01BQUEsMERBQThCO01BQUEsMEJBRXhCLDJDQUNOO2FBQUE7VUFBQSwwREFBUTtNQUFBLGlCQUNKO01BQUE7TUFBb0IsZ0VBRWQ7VUFBQSxpQkFDTjtVQUFBLCtDQUFBO1VBQUEsc0VBR007aUJBQUEsNEJBQ0Q7OztRQUo2QjtRQUFsQyxZQUFrQyxTQUFsQzs7O1FBUDBCO1FBQUE7UUFJTjtRQUFBOzs7O29CQ0w1QjtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
