/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.panel-body[_ngcontent-%COMP%] {\n    font-size: 17px;\n    font-weight: 600;\n    background-color: #ecf0f1;\n}\n.author[_ngcontent-%COMP%] {\n    display: inline-block;\n    font-style: italic;\n    font-size: 14px;\n    width: 80%;\n    padding-left: 15px;\n    position: relative;\n    top: -7px;\n}\n.config[_ngcontent-%COMP%] {\n    display: inline-block;\n    text-align: right;\n    font-size: 12px;\n    width: 19%;\n    position: relative;\n    top: -10px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy1saXN0L21lc3NhZ2UvbWVzc2FnZS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMtbGlzdC9tZXNzYWdlL21lc3NhZ2UuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
