/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './messages-list.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './message/message.component.ngfactory';
import * as i3 from './message/message.component';
import * as i4 from '../messages.service';
import * as i5 from '@angular/common';
import * as i6 from './messages-list.component';
const styles_MessagesListComponent:any[] = [i0.styles];
export const RenderType_MessagesListComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MessagesListComponent,data:{}});
function View_MessagesListComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-message',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_MessageComponent_0,
      i2.RenderType_MessageComponent)),i1.ɵdid(114688,(null as any),0,i3.MessageComponent,
      [i4.MessagesService],{message:[0,'message']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_MessagesListComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n        '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),1,
          (null as any),View_MessagesListComponent_1)),i1.ɵdid(802816,(null as any),
          0,i5.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,
              'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n\n']))],
      (_ck,_v) => {
        var _co:i6.MessagesListComponent = _v.component;
        const currVal_0:any = _co.messages;
        _ck(_v,5,0,currVal_0);
      },(null as any));
}
export function View_MessagesListComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-messages-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesListComponent_0,
      RenderType_MessagesListComponent)),i1.ɵdid(114688,(null as any),0,i6.MessagesListComponent,
      [i4.MessagesService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessagesListComponentNgFactory:i1.ComponentFactory<i6.MessagesListComponent> = i1.ɵccf('app-messages-list',
    i6.MessagesListComponent,View_MessagesListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy1saXN0L21lc3NhZ2VzLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMtbGlzdC9tZXNzYWdlcy1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMtbGlzdC9tZXNzYWdlcy1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy1saXN0L21lc3NhZ2VzLWxpc3QuY29tcG9uZW50LnRzLk1lc3NhZ2VzTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICA8ZGl2IGNsYXNzPVwiY29sLW1kLTggY29sLW1kLW9mZnNldC0yXCI+XG4gICAgICAgIDxhcHAtbWVzc2FnZVxuICAgICAgICAgICAgKm5nRm9yPVwibGV0IG1lc3NhZ2Ugb2YgbWVzc2FnZXNcIlxuICAgICAgICAgICAgW2lucHV0TWVzc2FnZV09XCJtZXNzYWdlXCJcbiAgICAgICAgPjwvYXBwLW1lc3NhZ2U+XG4gICAgPC9kaXY+XG48L2Rpdj5cblxuIiwiPGFwcC1tZXNzYWdlcy1saXN0PjwvYXBwLW1lc3NhZ2VzLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNFUTtNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUVJO0lBRkosV0FFSSxTQUZKOzs7O29CQUZSO01BQUE7TUFBaUIsMkNBQ2I7VUFBQTtVQUFBLDRDQUFzQztVQUFBLGlCQUNsQztVQUFBLG9EQUFBO1VBQUE7Y0FBQSwyQkFHZTtNQUNiLHVDQUNKOzs7UUFKTTtRQURKLFdBQ0ksU0FESjs7OztvQkNGUjtNQUFBO3NDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
