/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './logout.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './logout.component';
import * as i3 from '../auth.service';
import * as i4 from '@angular/router';
const styles_LogoutComponent:any[] = [i0.styles];
export const RenderType_LogoutComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'col-md-8 col-md-offset-2']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'button',[['class','btn btn-danger']],(null as any),
      [[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i2.LogoutComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.onLogout()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['Logout'])),(_l()(),
      i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),
      (null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
      i1.ɵdid(114688,(null as any),0,i2.LogoutComponent,[i3.AuthService,i4.Router],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const LogoutComponentNgFactory:i1.ComponentFactory<i2.LogoutComponent> = i1.ɵccf('app-logout',
    i2.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC9sb2dvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQvbG9nb3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQvbG9nb3V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9hdXRoL2xvZ291dC9sb2dvdXQuY29tcG9uZW50LnRzLkxvZ291dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cclxuICAgIDxidXR0b24gY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJvbkxvZ291dCgpXCI+TG9nb3V0PC9idXR0b24+XHJcbjwvZGl2PiIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUEsZ0JBQXNDLDJDQUNsQztNQUFBO01BQUE7UUFBQTtRQUFBO1FBQStCO1VBQUE7VUFBQTtRQUFBO1FBQS9CO01BQUEsZ0NBQW9ELDJDQUFlO2FBQUE7OztvQkNEdkU7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
