/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header/header.component.ngfactory';
import * as i3 from './header/header.component';
import * as i4 from '@angular/router';
import * as i5 from './error/error.component.ngfactory';
import * as i6 from './error/error.component';
import * as i7 from './error/error.service';
import * as i8 from './messages/messages.service';
import * as i9 from '@angular/http';
import * as i10 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),9,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'app-header',([] as any[]),(null as any),(null as any),(null as any),i2.View_HeaderComponent_0,
          i2.RenderType_HeaderComponent)),i1.ɵdid(114688,(null as any),0,i3.HeaderComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i1.ɵdid(212992,(null as any),
          0,i4.RouterOutlet,[i4.ChildrenOutletContexts,i1.ViewContainerRef,i1.ComponentFactoryResolver,
              [8,(null as any)],i1.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-error',([] as any[]),(null as any),
          (null as any),(null as any),i5.View_ErrorComponent_0,i5.RenderType_ErrorComponent)),
      i1.ɵdid(114688,(null as any),0,i6.ErrorComponent,[i7.ErrorService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,3,0);
    _ck(_v,8,0);
    _ck(_v,12,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵprd(4608,(null as any),i8.MessagesService,i8.MessagesService,[i9.Http,i7.ErrorService]),
      i1.ɵdid(49152,(null as any),0,i10.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i10.AppComponent> = i1.ɵccf('my-app',
    i10.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L01FQU4vbWFpbi1wcm9qZWN0L2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+XG4gICAgPGhyPlxuICAgIDxyb3V0ZXItb3V0bGV0Pjwvcm91dGVyLW91dGxldD5cbjwvZGl2PlxuPGFwcC1lcnJvcj48L2FwcC1lcnJvcj4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBdUIsMkNBQ25CO1VBQUE7dUNBQUEsVUFBQTtVQUFBLDJDQUF5QjtVQUFBLGFBQ3pCO1VBQUE7TUFBSSwyQ0FDSjtVQUFBO1VBQUEsbURBQUE7VUFBQTtjQUFBO01BQStCLHVDQUM3QjtNQUNOO1VBQUE7YUFBQTtVQUFBO0lBSkk7SUFFQTtJQUVKOzs7O29CQ0xBO01BQUE7YUFBQTthQUFBOzs7OyJ9
