/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './messages.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './messages-input/messages-input.component.ngfactory';
import * as i3 from './messages-input/messages-input.component';
import * as i4 from './messages.service';
import * as i5 from './messages-list/messages-list.component.ngfactory';
import * as i6 from './messages-list/messages-list.component';
import * as i7 from './messages.component';
const styles_MessagesComponent:any[] = [i0.styles];
export const RenderType_MessagesComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_MessagesComponent,data:{}});
export function View_MessagesComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'app-messages-input',([] as any[]),(null as any),(null as any),(null as any),
          i2.View_MessagesInputComponent_0,i2.RenderType_MessagesInputComponent)),
      i1.ɵdid(114688,(null as any),0,i3.MessagesInputComponent,[i4.MessagesService],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),
          i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','row']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'app-messages-list',([] as any[]),(null as any),
          (null as any),(null as any),i5.View_MessagesListComponent_0,i5.RenderType_MessagesListComponent)),
      i1.ɵdid(114688,(null as any),0,i6.MessagesListComponent,[i4.MessagesService],
          (null as any),(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),
          i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,3,0);
    _ck(_v,9,0);
  },(null as any));
}
export function View_MessagesComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-messages',
      ([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,
      RenderType_MessagesComponent)),i1.ɵdid(114688,(null as any),0,i7.MessagesComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MessagesComponentNgFactory:i1.ComponentFactory<i7.MessagesComponent> = i1.ɵccf('app-messages',
    i7.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9NRUFOL21haW4tcHJvamVjdC9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovTUVBTi9tYWluLXByb2plY3QvYXNzZXRzL2FwcC9tZXNzYWdlcy9tZXNzYWdlcy5jb21wb25lbnQudHMuTWVzc2FnZXNDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwicm93XCI+XHJcbiAgICA8YXBwLW1lc3NhZ2VzLWlucHV0PjwvYXBwLW1lc3NhZ2VzLWlucHV0PlxyXG48L2Rpdj5cclxuPGRpdiBjbGFzcz1cInJvd1wiPlxyXG4gICAgPGFwcC1tZXNzYWdlcy1saXN0PjwvYXBwLW1lc3NhZ2VzLWxpc3Q+XHJcbjwvZGl2PlxyXG4iLCI8YXBwLW1lc3NhZ2VzPjwvYXBwLW1lc3NhZ2VzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBaUIsMkNBQ2I7VUFBQTsrRUFBQTthQUFBO1VBQUEsNkJBQXlDLHVDQUN2QztpQkFBQSx3QkFDTjtVQUFBO1VBQUEsZ0JBQWlCLDJDQUNiO1VBQUE7VUFBQTthQUFBO1VBQUEsNkJBQXVDLHVDQUNyQztpQkFBQTtJQUpGO0lBR0E7Ozs7b0JDSko7TUFBQTtrQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
